version: '3.7'
services:
  mongo:
    image: mongo    
    container_name: mongo    
    volumes:      
      - mongodata:/data/db
    restart: always
    ports:
      - 27017:27017
    networks: 
      - inventory
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - mongo
    networks: 
      - inventory
  inventory-api:
    container_name: inventory-api
    image: inventoryapi
    build:
      context: ./inventory.api
      dockerfile: Dockerfile
    ports:
      - 9200:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Container
    depends_on:
      - mongo
    networks: 
      - inventory
volumes:
  mongodata:
networks: 
  inventory:
    name: inventory
    driver: bridge